### ISSUE TITLE
Cannot use 'in' operator to search for 'href' in undefined

### ISSUE THREAD

**Issue by umitkucuk** [Angelmmiguel/angelmm.rocks#4]
I have installed all packages and run `yarn start` command. I got an error that I don't know what it is.

![ss](https://user-images.githubusercontent.com/24843599/41800791-cc98ee44-767f-11e8-8f7b-4bd6133b3adc.PNG)

**Comment by Angelmmiguel** [comment]
Hello @umitkucuk,

Yes, it's a problem with preact and the Link component of nextjs. I've already [open an issue in the zeit/plugins repo](https://github.com/zeit/next-plugins/issues/191).

The problem is that the Link component checks if the href is includes in the props of the component. However, after migrating the project to preact, `child.props` is undefined using `react-hot-loader` (development). It works well in production.

Meanwhile the bug is resolved, you can edit the [`node_modules/next.js/dist/link.js` line 137](https://github.com/zeit/next.js/blob/canary/lib/link.js#L139) and add the following code:

```
if (child.props === undefined) {
  child = child[0];
}
```

**Comment by developit** [comment]
Updating to Preact 8.3.0 should fix this for you!

**Comment by Angelmmiguel** [comment]
I'm gonna update it. Thanks @developit !
